DROP DATABASE IF EXISTS instagram1;
-- CREATE DATABASE
CREATE DATABASE instagram1;
USE instagram1;

-- USERS TABLE
CREATE TABLE USERS(
    USERID INT AUTO_INCREMENT,
    INSTAID VARCHAR(40) NOT NULL UNIQUE,
    USERNAME VARCHAR(40) NOT NULL,
    PASSWORDID VARCHAR(30) NOT NULL,
    GENDER ENUM('FEMALE','MALE'),
    AGE TINYINT UNSIGNED CHECK (AGE > 13),
    MOBILE VARCHAR(10),
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY(USERID)
);

-- POSTS TABLE
CREATE TABLE POSTS(
    POSTID VARCHAR(10) NOT NULL,
    USERID INT,
    DESCRIPTION TEXT,
    TAGS TINYTEXT,
    VIEWS INT DEFAULT 0,
    LIKES INT DEFAULT 0,
    PRIMARY KEY(POSTID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

-- COMMENTS TABLE
CREATE TABLE COMMENTS(
    COMMENTID VARCHAR(10) NOT NULL,
    USERID INT,
    POSTID VARCHAR(10),
    COMMENT TINYTEXT NOT NULL,
    LIKES INT DEFAULT 0,
    PRIMARY KEY(COMMENTID),
    FOREIGN KEY(USERID) REFERENCES USERS(USERID),
    FOREIGN KEY(POSTID) REFERENCES POSTS(POSTID)
);

-- STORIES TABLE
CREATE TABLE STORIES (
    STORYID VARCHAR(20) NOT NULL,
    USERID INT,
    CONTENT TEXT NOT NULL,
    VIEWS INT DEFAULT 0,
    LIKES INT DEFAULT 0,
    EXPIRY DATETIME NOT NULL,
    PRIMARY KEY (STORYID),
    FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

-- INSERT USERS (AUTO_INCREMENT handles USERID)
INSERT INTO USERS (INSTAID, USERNAME, PASSWORDID, GENDER, AGE, MOBILE, EMAIL)
VALUES
('Kaushik','Kaushik@123','Kaushik(1608)','MALE',20,'9849757793','Kaushik@gmail.com'),
('ram','ram_16','ram','MALE',24,'8075423456','ram@gmail.com'),
('manoj','manoj87','manoj','MALE',26,'7856434567','manojanumula@gmail.com'),
('nithin','salaar_78','slrntn','MALE',21,'9876834324','nithinreddy@gmail.com'),
('sekhar','sekhar_98','sekhar','MALE',21,'9756438754','sekharbhai58@gmail.com');

-- INSERT POSTS
INSERT INTO POSTS (POSTID, USERID, DESCRIPTION, TAGS, VIEWS, LIKES) VALUES
('P101', 1, 'Enjoying coding journey', '#coding #python', 150, 25),
('P102', 2, 'Gym time 💪', '#fitness #health', 200, 40),
('P103', 3, 'Beautiful sunset 🌅', '#nature #photography', 180, 35),
('P104', 4, 'Weekend vibes', '#travel #fun', 220, 50);

-- INSERT COMMENTS
INSERT INTO COMMENTS (COMMENTID, USERID, POSTID, COMMENT, LIKES) VALUES
('C1', 2, 'P101', 'Nice post!', 10),
('C2', 3, 'P101', 'Keep going!', 5),
('C3', 1, 'P102', 'Great workout!', 8),
('C4', 4, 'P103', 'Amazing view!', 12),
('C5', 2, 'P104', 'Looks fun!', 6),
('C6', 1, 'P103', 'Beautiful capture!', 7);

-- INSERT STORIES
INSERT INTO STORIES (STORYID, USERID, CONTENT, VIEWS, LIKES, EXPIRY) VALUES
('S101', 1, 'Late night coding grind 💻', 120, 15, DATE_ADD(NOW(), INTERVAL 24 HOUR)),
('S102', 2, 'Post-workout protein shake 🥤', 140, 20, DATE_ADD(NOW(), INTERVAL 24 HOUR)),
('S103', 3, 'Coffee + Sunset = Perfect combo ☕🌅', 160, 25, DATE_ADD(NOW(), INTERVAL 24 HOUR)),
('S104', 4, 'Road trip sneak peek 🚗✨', 180, 30, DATE_ADD(NOW(), INTERVAL 24 HOUR));

-- CHECK DATA
SELECT * FROM USERS;
SELECT * FROM POSTS;
SELECT * FROM COMMENTS;
SELECT * FROM STORIES;